export const siteConfig={name:"R.W. Brewer Jr. Hope Without Color Foundation",motto:"INTEGRITAS • HONOR • FAMILIA",donationUrl:"https://buy.stripe.com/test_fZufZhfwFb3n5lifhL6g801",contact:{email:"",phone:"",location:""},socials:[] as {label:string;url:string}[]};
export const programs=[
 {icon:"🥬",category:"Food Access & Community Distribution",title:"Nourish Hope",tagline:"Good food creates stronger foundations.",status:"Partnerships forming",text:"Expands access to nutritious food through community distribution events, local partnerships, and responsive food-access support.",features:["Community Food Days","Fresh Food Partnerships","Family Food Boxes","Emergency Food Support","Resource Connection"],actions:["Find food support","Become a food partner"]},
 {icon:"🌱",category:"Nutrition Education & Healthy Living",title:"Healthy Roots",tagline:"Practical knowledge for healthier everyday choices.",status:"Upcoming program",text:"Turns nutrition and wellness information into practical tools families can use within real-world schedules, budgets, and circumstances.",features:["Smart Shopping","Build a Balanced Plate","Healthy Food on a Budget","Family Nutrition","Healthy Habits"],actions:["View workshops","Host a workshop"]},
 {icon:"📖",category:"Tutoring & Literacy",title:"Bright Futures Learning Lab",tagline:"Confidence grows when learning feels possible.",status:"Upcoming program",text:"Helps students strengthen foundational academic skills and confidence through tutoring, literacy support, and mentorship.",features:["Reading Support","Homework Help","Foundational Math","Learning Confidence","Family Resources","Mentorship"],actions:["Request learning support","Become a tutor"]},
 {icon:"🎓",category:"Education Opportunity",title:"Open Doors Scholarship Fund",tagline:"Opportunity should not end where financial barriers begin.",status:"Applications open soon",text:"Planned to help students pursue approved educational opportunities through financial support that recognizes determination and potential.",features:["College","Community College","Trade School","Vocational Certification","Career Training"],actions:["Scholarship updates","Support a student"]},
 {icon:"🧭",category:"Career Readiness & Economic Opportunity",title:"Forward Pathways",tagline:"Prepare today. Move forward tomorrow.",status:"Partnerships forming",text:"Helps individuals build practical skills, confidence, and connections for employment, training, and career opportunities.",features:["Resume Ready","Interview Confidence","Professional Communication","Digital Readiness","Career Exploration","Mentor Connection"],actions:["Join a workshop","Become a career partner"]},
 {icon:"🤝",category:"Community Learning, Wellness & Connection",title:"Stronger Together Community Series",tagline:"Knowledge grows stronger when communities learn together.",status:"Upcoming program",text:"Brings individuals, families, experts, and local organizations together around practical topics that improve everyday life.",features:["Family Wellness","Financial Foundations","Education Nights","Healthy Families","Career Conversations","Youth Opportunity"],actions:["See upcoming events","Host or sponsor an event"]}
];
